language: node_js
node_js:
- node
script:
- npm run test
deploy:
  provider: npm
  email: jpoehnelt@google.com
  api_key:
    secure: m0IoJVgC7xnhxJvQDk4jUKlOmT253xN9C2UuGDvEP/h/24OE0SUQUp51+5CMTCNfsp9v/OZXS3nOqFaJe2RGovgOEtqwUukWg17+pjb/y/Iszsq22i9x6dPu7ItiYy6D/zvUx8KJYLpB0YkQ15VEEhdsZS+jWuojVm+6I7s8JyvF0PTO7n4W7eDRcQ22kcM5rMMaa3lvjPys09hQBMGeOhc/0WdG9QWDvVJFscXHL3sgvcCCzXpD/ihbnfqLqo2W3HXtQxdwC6QEHp9elLaou+haEHjQm4UFGko0IzZU/gutdQruxopKj+KagubBzqwf5SmHlEBmS9DbBNhDIE3WMeOS/oy1ahdJOUvotRSIlmSChxEfmwwuVt7264xjhuBKNHisLdC+bUnV8BHnyFG3uetE8u6Yav2VCYSJWS34lpnxUNwILlHWW6scVexSBOdT+rQ7ZuVGQ8aKUtOc9y+6rn8hBWPYcC03kGfv6COdi64amO2OgNTR4enueoBQutQztHPl/7Y+fh52Mhk4CM6Tz/x+s5lpFjjfHDsrrHlJmPIQ0a6nzng2SIMDsEeGhN1+6wqGaOYDP5FMh2mKgUy6QgSEDINnYF/1vu0SINQ4YuoyZKbNraLDHB8elpjOshfEdJ8hMCKPjl4SAfmTs/+6Hy+SybCWIpJ/9DH0m3N3tbY=
  on:
    tags: true
