language: node_js
node_js:
- node
script:
- npm run test
deploy:
  provider: npm
  email: jpoehnelt@google.com
  api_key:
    secure: lGoiTwxyV1lhfR4HyKTA1E9FxiwH3+X4cC4wMvP7g+1F9yoe4fI6PYsCugmGoIB/b+Yxgtn7IP8hAToRnK4lsQ8DKEoPwHuGfJbtuuX0BwHpGq1y1ZpMLd8LHg//PAB2Cq86GK8/ryfF8lFyay+Sz2aICj8bB+cY4Tq4V41k8h/reS2H2b0zePu24wo/xRC3Hqr+096izCinRGwoshK67ybn4O+gsBL5iUjl8kM2H+GuKMTe8q14lkw31Oq7dqYLhfFMuEd0Wia24MlwN+ymXRFBIoSXoHntQktIfqbuos97DLe3t6gF7Ofm6sShzcsavESfseLMDFt7RyFlr6HgVdluuCi47GorRahLpEZImBNASGxx9aTd2rflL8ouLLcVruBB/xkY4rBMCGs0uKmJbLP/ITJ/Ps6lF1oVjRCYnn0vqfoBJUcpxP1mx3RP/8TCuXr5+lMFZtHkD2wuGBKOoFpgN2yxkhC3UcaiZ72lhdkVOXwmGMCqSjFwzA3VyTLrySkUv3/A6lcxPPdw0eI7wQ3sq/Kt3EbxwkKco+K+w/KzqBZuoYvmhNnPoiFf2NV67jOP3cR5i1TaFlQMalaCKxVmqqKmJlgLN4lcrNO6FCuSPRgPpT+Kp5FHUtzvpZgGzkMYuyVQ5PxW9uQ5k4YrqVXHKFjbXbT7JGIhokcg/4w=
  on:
    tags: true
